### ISSUE TITLE
The link to the CppAD documentaion is out of date

### ISSUE THREAD

**Issue by bradbell** [conda-forge/cppad-feedstock#19]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

The link to the CppAD documentation on 
https://anaconda.org/conda-forge/cppad
points to the web page
https://coin-or.github.io/CppAD/doc/cppad.htm

This is fixed at version cppad-20221105 which is just before the documentation was converted from using OMhelp to using Sphinx.

The current documentation can be found at
https://cppad.readthedocs.io/

### Installed packages

```shell
Does not apply to this issue
```

### Environment info

```shell
Does not apply to this issue
```

**Comment by traversaro** [comment]
@bradbell fixed by https://github.com/conda-forge/cppad-feedstock/pull/20 and https://github.com/conda-forge/cppad-feedstock/pull/21, let us know if there are still problems.

**Comment by bradbell** [comment]
@traversaro The fix looks good to me. 

I have one other minor comment about
https://github.com/conda-forge/cppad-feedstock/blob/main/recipe/meta.yaml
That is not urgent (EPL-2.0 is correct), but perhaps you can update when version 2024 comes out.

CppAD has converted to using SPDX for license specifications; see
https://spdx.org/licenses/

Using this notation, the actual license in the code is
 EPL-2.0 OR GPL-2.0-or-later
see Secondary License on
https://www.eclipse.org/legal/epl-2.0/faq.php#epl-secondary

**Comment by traversaro** [comment]
Perfect, thanks! 

> @traversaro The fix looks good to me.
> 
> I have one other minor comment about https://github.com/conda-forge/cppad-feedstock/blob/main/recipe/meta.yaml That is not urgent (EPL-2.0 is correct), but perhaps you can update when version 2024 comes out.
> 
> CppAD has converted to using SPDX for license specifications; see https://spdx.org/licenses/
> 
> Using this notation, the actual license in the code is EPL-2.0 OR GPL-2.0-or-later see Secondary License on https://www.eclipse.org/legal/epl-2.0/faq.php#epl-secondary

Thanks, I opened https://github.com/conda-forge/cppad-feedstock/issues/22 to remember this.
